version: "3.9"

services:
  web:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:80"
    command: "uvicorn app.main:app --host 0.0.0.0 --port 80"

  db:
    image: postgres
    environment:
      POSTGRES_DB: memento
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
